name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Περνάμε ρητά δοκιμασμένες εκδόσεις για να υπάρχει πάντα το plugin:
          pip install "pytest==8.2.0" "pytest-cov==5.0.0"
          python -c "import sys,pytest; print('PYTEST:', pytest.__version__);"

      - name: Run tests with coverage
        run: |
          pytest -vv --maxfail=1 --disable-warnings \
                 --cov=. --cov-report=term --cov-report=xml:coverage.xml

      - name: Upload coverage report
        if: ${{ always() && hashFiles('coverage.xml') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
